using static SyncNetPro.Iso8583.IsoFieldContent;
using static SyncNetPro.Iso8583.IsoLengthType;

namespace SyncNetPro.Iso8583;

/// <summary>Salinan tabel field <c>SyncNet.IsoMessage.FieldFormatter</c> SDK lama (diverifikasi golden test).</summary>
internal static class LegacySpec
{
    public static IsoSpec Create() => IsoSpec.Create(s => s
        .Field(2, LLVar, N, 19, "Primary Account Number")
        .Field(3, Fixed, N, 6, "Processing Code")
        .Field(4, Fixed, N, 12, "Amount Transaction")
        .Field(5, Fixed, N, 12, "Amount Settlement")
        .Field(7, Fixed, N, 14, "Transmission Date and Time")
        .Field(9, Fixed, N, 8, "Conversion Rate, Settlement")
        .Field(11, Fixed, N, 12, "Systems Trace Audit Number")
        .Field(12, Fixed, N, 6, "Time, Local Transaction")
        .Field(13, Fixed, N, 4, "Date, Local Transaction")
        .Field(14, Fixed, N, 4, "Date, Expiration")
        .Field(15, Fixed, N, 8, "Date, Settlement")
        .Field(16, Fixed, N, 4, "Date, Conversion")
        .Field(17, Fixed, N, 4, "Date, Capture")
        .Field(18, Fixed, N, 4, "Merchant Type")
        .Field(22, Fixed, N, 3, "POS Entry Mode")
        .Field(23, Fixed, N, 3, "Card Sequence Number")
        .Field(24, Fixed, N, 4, "Network Identification Number")
        .Field(25, Fixed, N, 2, "POS Condition Code")
        .Field(26, Fixed, N, 2, "POS PIN Capture Code")
        .Field(27, Fixed, N, 1, "Authorization ID Response Length")
        .Field(28, Fixed, An, 9, "Amount, Transaction Fee")
        .Field(29, Fixed, An, 9, "Amount, Settlement Fee")
        .Field(30, Fixed, An, 9, "Amount, Transaction Processing Fee")
        .Field(31, Fixed, An, 9, "Amount, Settle Processing Fee")
        .Field(32, LLVar, N, 11, "Acquiring Institution ID Code")
        .Field(33, LLVar, N, 11, "Forwarding Institution ID Code")
        .Field(35, LLVar, An, 37, "Track 2 Data")
        .Field(37, Fixed, An, 12, "Retrieval Reference Number")
        .Field(38, Fixed, An, 6, "Authorization ID Response")
        .Field(39, Fixed, An, 4, "Response Code")
        .Field(40, Fixed, N, 3, "Service Restriction Code")
        .Field(41, Fixed, An, 16, "Card Acceptor Terminal ID")
        .Field(42, Fixed, An, 15, "Card Acceptor ID Code")
        .Field(43, Fixed, Ans, 40, "Card Acceptor Name Location")
        .Field(44, LLVar, N, 25, "Additional Response Data")
        .Field(45, LLVar, An, 76, "Track 1 Data")
        .Field(48, LLLVar, Ans, 999, "Additional Data")
        .Field(49, Fixed, N, 3, "Currency Code, Transaction")
        .Field(50, Fixed, N, 3, "Currency Code, Settlement")
        .Field(52, Fixed, An, 16, "PIN Data")
        .Field(53, LLLVar, An, 100, "Security Related Control Information")
        .Field(54, LLLVar, Ans, 120, "Additional Amounts")
        .Field(56, LLVar, Ans, 99, "Message Reason Code")
        .Field(57, LLLVar, N, 3, "Authorization Life-cycle Code")
        .Field(58, LLLVar, N, 11, "Authorizing Agent Institution")
        .Field(59, LLLVar, Ans, 255, "Echo Data")
        .Field(60, LLLVar, Ans, 999, "Private Field")
        .Field(61, LLLVar, Ans, 999, "Private Field")
        .Field(62, LLLVar, Ans, 999, "Private Field")
        .Field(63, LLLVar, Ans, 999, "Private Field")
        .Field(64, Fixed, N, 2, "Split Transaction")
        .Field(65, Fixed, N, 2, "Amount Flag")
        .Field(66, Fixed, N, 1, "Settlement Code")
        .Field(67, Fixed, N, 2, "Extended Payment Code")
        .Field(70, Fixed, N, 3, "Network Management Information Code")
        .Field(73, Fixed, N, 6, "Date, Action")
        .Field(74, Fixed, N, 10, "Credits, Number")
        .Field(75, Fixed, N, 10, "Credits, Reversal Number")
        .Field(76, Fixed, N, 10, "Debits, Number")
        .Field(77, Fixed, N, 10, "Debits, Reversal Number")
        .Field(78, Fixed, N, 10, "Transfer, Number")
        .Field(79, Fixed, N, 10, "Transfer, Reversal Number")
        .Field(80, Fixed, N, 10, "Inquiries, Number")
        .Field(81, Fixed, N, 10, "Authorizations, Number")
        .Field(82, Fixed, N, 12, "Credits, Processing Fee Amount")
        .Field(83, Fixed, N, 12, "Credits, Transaction Fee Amount")
        .Field(84, Fixed, N, 12, "Debits, Processing Fee Amount")
        .Field(85, Fixed, N, 12, "Debits, Transaction Fee Amount")
        .Field(86, Fixed, N, 16, "Credits, Amount")
        .Field(87, Fixed, N, 16, "Credits, Reversal Amount")
        .Field(88, Fixed, N, 16, "Debits, Amount")
        .Field(89, Fixed, N, 16, "Debits, Reversal Amount")
        .Field(90, Fixed, An, 42, "Original Data Elements")
        .Field(91, Fixed, An, 1, "File Update Code")
        .Field(95, Fixed, An, 42, "Replacement Amounts")
        .Field(97, Fixed, An, 17, "Amount, Net Settlement")
        .Field(98, LLVar, Ans, 30, "Payee")
        .Field(100, LLVar, N, 11, "Receiving Institution ID Code")
        .Field(101, LLVar, N, 17, "File Name")
        .Field(102, LLVar, Ans, 28, "Account Identification 1")
        .Field(103, LLVar, Ans, 28, "Account Identification 2")
        .Field(104, LLVar, N, 34, "Transaction Description")
        .Field(118, LLLVar, N, 100, "Payments, Number")
        .Field(119, LLLVar, N, 10, "Payments, Reversal Number")
        .Field(120, Fixed, N, 2, "Authorization Profile")
        .Field(123, LLLVar, An, 15, "POS Data Code")
        .Field(124, Fixed, N, 48, "Fees Structure")
        .Field(125, LLVar, N, 32, "Transaction Number")
        .Field(126, LLVar, Ans, 25, "Time Transaction Received")
        .Field(127, LLLLLLVar, Ans, 999_999, "Private Field"));
}
