using System.ComponentModel.DataAnnotations;

namespace SyncNetApi.Dtos.CardProducts
{
    /// <summary>Id is generated by Postgres (GENERATED ALWAYS AS IDENTITY) — never supplied by
    /// the caller. ProfileName/LastSeqNr are never accepted here (see DTO note).</summary>
    public class CreateCardProductRequest
    {
        [Required, MaxLength(30)]
        public string Issuer { get; set; } = string.Empty;

        [Required, MaxLength(30)]
        public string Product { get; set; } = string.Empty;

        [Required, MaxLength(12)]
        public string PanPrefix { get; set; } = string.Empty;

        [Required, Range(1, short.MaxValue)]
        public short PanLength { get; set; }

        [Required, MaxLength(30)]
        public string CardType { get; set; } = string.Empty;
    }
}
