<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="MinVer" Version="8.0.0" />

    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

</Project>
