using System.ComponentModel.DataAnnotations;

namespace SyncNetApi.Dtos.AgentBanks
{
    /// <summary>Id is generated by Postgres (GENERATED ALWAYS AS IDENTITY) — never supplied by
    /// the caller. AccName is intentionally not [Required] — legacy IsValid() never checks it
    /// for presence.</summary>
    public class CreateAgentBankRequest
    {
        [Required, MaxLength(50)]
        public string Nmid { get; set; } = string.Empty;

        [Required, MaxLength(50)]
        public string BankName { get; set; } = string.Empty;

        [Required, MaxLength(6)]
        public string BankCode { get; set; } = string.Empty;

        [Required, MaxLength(20)]
        public string AccNumber { get; set; } = string.Empty;

        [MaxLength(50)]
        public string? AccName { get; set; }
    }
}
