using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using SyncNetApi.Common;
using SyncNetApi.Data;
using SyncNetApi.Dtos.ProductFees;
using SyncNetApi.Entities;
using SyncNetApi.Services.Audit;

namespace SyncNetApi.Services.ProductFees
{
    public class ProductFeeService : IProductFeeService
    {
        private readonly SyncNetDbContext _context;
        private readonly IAuditService _audit;

        public ProductFeeService(SyncNetDbContext context, IAuditService audit)
        {
            _context = context;
            _audit = audit;
        }

        // Mirrors legacy ProductFeesGetRecords — INNER JOIN Product Master (a fee row whose
        // product no longer exists drops out of the list, same as legacy), LEFT JOIN
        // Merchant/SubMerchant since those relations are optional.
        public async Task<IReadOnlyList<ProductFeeDto>> GetRecordsAsync(string? filter = null)
        {
            var query = from f in _context.Fees.AsNoTracking()
                        join p in _context.Products.AsNoTracking() on f.product_id equals p.product_code
                        join m in _context.Merchants.AsNoTracking() on f.merchant_id equals m.merchant_id into gm
                        from m in gm.DefaultIfEmpty()
                        join sm in _context.SubMerchants.AsNoTracking() on f.submerchant_id equals sm.submerchant_id into gsm
                        from sm in gsm.DefaultIfEmpty()
                        select new { f, ProductName = p.product_name, MerchantName = m == null ? null : m.name, SubmerchantName = sm == null ? null : sm.name };

            if (!string.IsNullOrWhiteSpace(filter))
            {
                var flt = filter.Sanitize().ToLower();
                query = query.Where(x => (x.f.product_id ?? "").ToLower().Contains(flt)
                    || (x.ProductName ?? "").ToLower().Contains(flt)
                    || (x.f.group_name ?? "").ToLower().Contains(flt)
                    || (x.f.subgroup_name ?? "").ToLower().Contains(flt));
            }

            var list = await query.OrderBy(x => x.f.id).ToListAsync();
            return list.Select(x => ToDto(x.f, x.ProductName, x.MerchantName, x.SubmerchantName)).ToList();
        }

        public async Task<ProductFeeDto?> GetByIdAsync(long id)
        {
            var entity = await _context.Fees.AsNoTracking().FirstOrDefaultAsync(x => x.id == id);
            if (entity == null) return null;

            var productName = await _context.Products.AsNoTracking()
                .Where(p => p.product_code == entity.product_id).Select(p => p.product_name).FirstOrDefaultAsync();
            var merchantName = string.IsNullOrEmpty(entity.merchant_id) ? null : await _context.Merchants.AsNoTracking()
                .Where(m => m.merchant_id == entity.merchant_id).Select(m => m.name).FirstOrDefaultAsync();
            var submerchantName = string.IsNullOrEmpty(entity.submerchant_id) ? null : await _context.SubMerchants.AsNoTracking()
                .Where(sm => sm.submerchant_id == entity.submerchant_id).Select(sm => sm.name).FirstOrDefaultAsync();

            return ToDto(entity, productName, merchantName, submerchantName);
        }

        public async Task<ProductFeeDto> CreateAsync(CreateProductFeeRequest request, string actingUser)
        {
            if (!await _context.Products.AsNoTracking().AnyAsync(p => p.product_code == request.ProductId))
                throw new ValidationException($"Product '{request.ProductId}' does not exist.");

            if (!string.IsNullOrEmpty(request.MerchantId) && !await _context.Merchants.AsNoTracking().AnyAsync(m => m.merchant_id == request.MerchantId))
                throw new ValidationException($"Merchant '{request.MerchantId}' does not exist.");

            ValidateFeeTotals(request.FeeType, request.FixedFee, request.FixedFeeAcq, request.FixedFeeIss, request.FixedFeeSwt,
                request.PercentFeeAcq, request.PercentFeeIss, request.PercentFeeSwt);

            // id is GENERATED BY DEFAULT AS IDENTITY — do not assign manually (see entity note).
            var entity = new SwFees
            {
                product_id = request.ProductId,
                merchant_id = request.MerchantId,
                submerchant_id = request.SubmerchantId,
                group_name = request.GroupName,
                subgroup_name = request.SubgroupName,
                fee_type = request.FeeType,
                fixed_fee = request.FixedFee,
                fixed_fee_acq = request.FixedFeeAcq,
                fixed_fee_iss = request.FixedFeeIss,
                fixed_fee_swt = request.FixedFeeSwt,
                percent_fee = request.PercentFee,
                percent_fee_acq = request.PercentFeeAcq,
                percent_fee_iss = request.PercentFeeIss,
                percent_fee_swt = request.PercentFeeSwt
            };

            _context.Fees.Add(entity);
            await _context.SaveChangesAsync();

            _audit.LogInsert(entity, "sw_fees", actingUser);
            await _context.SaveChangesAsync();

            return ToDto(entity, null, null, null);
        }

        public async Task<ProductFeeDto> UpdateAsync(long id, UpdateProductFeeRequest request, string actingUser)
        {
            var entity = await _context.Fees.FirstOrDefaultAsync(x => x.id == id)
                ?? throw new NotFoundException($"Product fee '{id}' not found.");

            ValidateFeeTotals(request.FeeType, request.FixedFee, request.FixedFeeAcq, request.FixedFeeIss, request.FixedFeeSwt,
                request.PercentFeeAcq, request.PercentFeeIss, request.PercentFeeSwt);

            var before = ToDto(entity, null, null, null);
            entity.fee_type = request.FeeType;
            entity.fixed_fee = request.FixedFee;
            entity.fixed_fee_acq = request.FixedFeeAcq;
            entity.fixed_fee_iss = request.FixedFeeIss;
            entity.fixed_fee_swt = request.FixedFeeSwt;
            entity.percent_fee = request.PercentFee;
            entity.percent_fee_acq = request.PercentFeeAcq;
            entity.percent_fee_iss = request.PercentFeeIss;
            entity.percent_fee_swt = request.PercentFeeSwt;

            _audit.LogUpdate(before, ToDto(entity, null, null, null), "sw_fees", actingUser);

            await _context.SaveChangesAsync();
            return ToDto(entity, null, null, null);
        }

        public async Task DeleteAsync(long id, string actingUser)
        {
            var entity = await _context.Fees.FirstOrDefaultAsync(x => x.id == id)
                ?? throw new NotFoundException($"Product fee '{id}' not found.");

            _context.Fees.Remove(entity);
            _audit.LogDelete(entity, "sw_fees", actingUser);

            await _context.SaveChangesAsync();
        }

        // Mirrors legacy IsValid(): Fixed fees must sum exactly to FixedFee; Percent fees must
        // sum exactly to 100.
        private static void ValidateFeeTotals(string feeType, int? fixedFee, int? fixedFeeAcq, int? fixedFeeIss, int? fixedFeeSwt,
            decimal? percentFeeAcq, decimal? percentFeeIss, decimal? percentFeeSwt)
        {
            if (feeType == "0")
            {
                var totalFixed = (fixedFeeAcq ?? 0) + (fixedFeeIss ?? 0) + (fixedFeeSwt ?? 0);
                if (totalFixed != (fixedFee ?? 0))
                    throw new ValidationException($"Total merchant, sub merchant and switch fees must be IDR {fixedFee ?? 0}.");
            }
            else
            {
                var totalPercent = (percentFeeAcq ?? 0) + (percentFeeIss ?? 0) + (percentFeeSwt ?? 0);
                if (totalPercent != 100)
                    throw new ValidationException("Total merchant, sub merchant and switch fees must be 100%.");
            }
        }

        private static ProductFeeDto ToDto(SwFees e, string? productName, string? merchantName, string? submerchantName) => new(
            e.id, e.product_id, productName, e.merchant_id, merchantName, e.submerchant_id, submerchantName,
            e.group_name, e.subgroup_name, e.fee_type ?? "0", e.fixed_fee, e.fixed_fee_acq, e.fixed_fee_iss, e.fixed_fee_swt,
            e.percent_fee, e.percent_fee_acq, e.percent_fee_iss, e.percent_fee_swt);
    }
}
