<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SyncNetPro.Sdk</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageId>SyncNetPro.Sdk</PackageId>
    <Description>SDK untuk membangun interface inbound/outbound SyncNet: host, handler, kanal Core, konfigurasi node, command port, trace &amp; log.</Description>
    <PackageTags>syncnet;switching;interface;iso8583</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="MinVer" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SyncNetPro.Contracts\SyncNetPro.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SyncNetPro.Sdk.Tests" />
  </ItemGroup>

</Project>
