using System.ComponentModel.DataAnnotations;

namespace SyncNetApi.Dtos.CardProductLimits
{
    /// <summary>Id is generated by Postgres (GENERATED ALWAYS AS IDENTITY). last_update/
    /// update_by are always server-set — never accepted from the client (matches legacy).
    /// Only ProductId/Channel are actually validated as mandatory by legacy IsValid(); every
    /// nr_*/amt_* field is optional (defaults to null/0).</summary>
    public class CreateCardProductLimitRequest
    {
        [Required]
        public int ProductId { get; set; }

        [Required, MaxLength(4)]
        public string Channel { get; set; } = string.Empty;

        public int? AmtPurchasePerTran { get; set; }
        public int? AmtCashPerTran { get; set; }
        public int? AmtPaymentPerTran { get; set; }
        public int? AmtTransferPerTran { get; set; }

        public int? NrInquiryDaily { get; set; }
        public int? NrPurchaseDaily { get; set; }
        public int? NrCashDaily { get; set; }
        public int? NrPaymentDaily { get; set; }
        public int? NrTransferDaily { get; set; }
        public int? AmtPurchaseDaily { get; set; }
        public int? AmtCashDaily { get; set; }
        public int? AmtPaymentDaily { get; set; }
        public int? AmtTransferDaily { get; set; }

        public int? NrInquiryWeekly { get; set; }
        public int? NrPurchaseWeekly { get; set; }
        public int? NrCashWeekly { get; set; }
        public int? NrPaymentWeekly { get; set; }
        public int? NrTransferWeekly { get; set; }
        public int? AmtPurchaseWeekly { get; set; }
        public int? AmtCashWeekly { get; set; }
        public int? AmtPaymentWeekly { get; set; }
        public int? AmtTransferWeekly { get; set; }

        public int? NrInquiryMonthly { get; set; }
        public int? NrPurchaseMonthly { get; set; }
        public int? NrCashMonthly { get; set; }
        public int? NrPaymentMonthly { get; set; }
        public int? NrTransferMonthly { get; set; }
        public int? AmtPurchaseMonthly { get; set; }
        public int? AmtCashMonthly { get; set; }
        public int? AmtPaymentMonthly { get; set; }
        public int? AmtTransferMonthly { get; set; }
    }
}
