// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SyncNetApi.Data;

#nullable disable

namespace SyncNetApi.Data.Migrations
{
    [DbContext(typeof(SyncNetDbContext))]
    [Migration("20260903125321_AddPasswordResetFields")]
    partial class AddPasswordResetFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SyncNetApi.Entities.BlacklistedToken", b =>
                {
                    b.Property<string>("Jti")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Jti");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("api_token_blacklist", "public");
                });

            modelBuilder.Entity("SyncNetApi.Entities.DashboardMenus", b =>
                {
                    b.Property<int>("menu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("menu_id"));

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("level_1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("level_2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("level_3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("level_4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("menu_id");

                    b.ToTable("dashboard_menu", "public");
                });

            modelBuilder.Entity("SyncNetApi.Entities.DashboardRoleMenu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("flag_add")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("flag_delete")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("flag_edit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("menu_id")
                        .HasColumnType("integer");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("dashboard_role_menu", "public");
                });

            modelBuilder.Entity("SyncNetApi.Entities.DashboardRoles", b =>
                {
                    b.Property<string>("role_name")
                        .HasColumnType("text");

                    b.Property<string>("flag_add")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("flag_delete")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("flag_edit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role_desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("role_name");

                    b.ToTable("dashboard_role", "public");
                });

            modelBuilder.Entity("SyncNetApi.Entities.DashboardUserLog", b =>
                {
                    b.Property<long>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("log_id"));

                    b.Property<DateTime>("date_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("host_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("host_agent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("host_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("log_id");

                    b.ToTable("dashboard_user_log", "public");
                });

            modelBuilder.Entity("SyncNetApi.Entities.DashboardUserReset", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime?>("consumed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("requested_ip")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("time_request")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("user_name")
                        .HasColumnType("text");

                    b.Property<string>("vcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("user_name");

                    b.HasIndex("vcode");

                    b.ToTable("dashboard_user_reset", "public");
                });

            modelBuilder.Entity("SyncNetApi.Entities.DashboardUsers", b =>
                {
                    b.Property<string>("user_name")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("last_login")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("max_retry")
                        .HasColumnType("integer");

                    b.Property<bool?>("must_change_password")
                        .HasColumnType("boolean");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("retry")
                        .HasColumnType("integer");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_name");

                    b.HasIndex("email");

                    b.ToTable("dashboard_user", "public");
                });

            modelBuilder.Entity("SyncNetApi.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserName");

                    b.ToTable("api_refresh_token", "public");
                });

            modelBuilder.Entity("SyncNetApi.Entities.SwAudit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("newvalue")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("oldvalue")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("tablename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("sw_audit", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
