-- ============================================================================
-- ConvertManualIdsToIdentity.sql
--
-- Purpose : Convert legacy PK columns that are currently populated by the
--           application via "MAX(id) + 1" (see entity/service comments such
--           as SwBank, SwGroup, SwAccount, SwNodes, DashboardRoleMenu, etc.)
--           into native PostgreSQL IDENTITY columns, so the database becomes
--           the single source of truth for PK generation.
--
-- Scope   : Only surrogate PK columns whose sole purpose is "next available
--           integer" are included. Columns that are picked/assigned by the
--           user or caller (e.g. sw_routes_by_bin.group_id, dashboard_menu.
--           menu_id) are intentionally EXCLUDED — see plan notes.
--
-- Mode    : GENERATED BY DEFAULT AS IDENTITY (not ALWAYS). This still lets
--           existing application code insert an explicit id without error
--           during the transition window, while letting new inserts that
--           omit the column get a DB-generated value. Revisit to ALWAYS
--           once Phase 2 (C# code changes) is complete and deployed, if
--           desired — see companion script ConvertManualIdsToIdentity_Tighten.sql
--           (not included yet).
--
-- Safe to re-run: idempotent — already-identity columns are skipped.
--
-- IMPORTANT: This script only touches the database. It does NOT change any
-- C# entity/service code. Application code that still computes
-- MaxAsync(...) + 1 and assigns the id explicitly will continue to work
-- unchanged after this script runs (BY DEFAULT allows explicit values).
-- ============================================================================

BEGIN;

DO $do$
DECLARE
    r RECORD;
    v_identity text;
BEGIN
    FOR r IN
        SELECT * FROM (VALUES
            ('public.sw_bank',             'id'),
            ('public.sw_brand',            'id'),
            ('public.sw_group',            'group_id'),
            ('public.sw_accounts',         'id'),
            ('public.sw_margin_merchant',  'id'),
            ('public.sw_margin_supplier',  'id'),
            ('public.sw_merchant_product', 'id'),
            ('public.sw_product_mapping',  'id'),
            ('public.sw_routes_by_source', 'id'),
            ('public.sw_crypto_keys',      'id'),
            ('public.sw_nodes',            'node_id'),
            ('public.sw_jobs',             'job_id'),
            ('public.sw_support_members',  'member_id'),
            ('public.sw_support_teams',    'team_id'),
            ('public.sw_product_bins',     'id'),
            ('public.sw_term_limit',       'id'),
            ('public.dashboard_role_menu', 'id'),
            ('public.va_trans_request',    'tran_nr')
        ) AS t(tbl, col)
    LOOP
        SELECT identity_generation INTO v_identity
        FROM information_schema.columns
        WHERE table_schema = split_part(r.tbl, '.', 1)
          AND table_name   = split_part(r.tbl, '.', 2)
          AND column_name  = r.col;

        IF v_identity IS NULL THEN
            EXECUTE format(
                'ALTER TABLE %s ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
                r.tbl, r.col
            );

            -- Seed the new sequence so the next generated value continues
            -- after the current max, instead of restarting at 1.
            EXECUTE format(
                'SELECT setval(pg_get_serial_sequence(%L, %L), COALESCE((SELECT MAX(%I) FROM %s), 0) + 1, false)',
                r.tbl, r.col, r.col, r.tbl
            );

            RAISE NOTICE 'Converted %.% to IDENTITY (BY DEFAULT)', r.tbl, r.col;
        ELSE
            RAISE NOTICE 'Skipped %.% — already identity (%)', r.tbl, r.col, v_identity;
        END IF;
    END LOOP;
END
$do$;

COMMIT;

-- ============================================================================
-- Verification — run after commit to confirm every column converted.
-- Expect: is_identity = YES, identity_generation = BY DEFAULT for all rows.
-- ============================================================================
-- SELECT table_name, column_name, is_identity, identity_generation, column_default
-- FROM information_schema.columns
-- WHERE table_schema = 'public'
--   AND (table_name, column_name) IN (
--     ('sw_bank','id'), ('sw_brand','id'), ('sw_group','group_id'),
--     ('sw_accounts','id'), ('sw_margin_merchant','id'), ('sw_margin_supplier','id'),
--     ('sw_merchant_product','id'), ('sw_product_mapping','id'),
--     ('sw_routes_by_source','id'), ('sw_crypto_keys','id'), ('sw_nodes','node_id'),
--     ('sw_jobs','job_id'), ('sw_support_members','member_id'),
--     ('sw_support_teams','team_id'), ('sw_product_bins','id'),
--     ('sw_term_limit','id'), ('dashboard_role_menu','id'), ('va_trans_request','tran_nr')
--   )
-- ORDER BY table_name;

-- ============================================================================
-- Rollback (manual, run only if needed — reverts to plain non-identity int
-- columns; the underlying sequence is dropped along with the identity):
-- ============================================================================
-- ALTER TABLE public.sw_bank             ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_brand            ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_group            ALTER COLUMN group_id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_accounts         ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_margin_merchant  ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_margin_supplier  ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_merchant_product ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_product_mapping  ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_routes_by_source ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_crypto_keys      ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_nodes            ALTER COLUMN node_id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_jobs             ALTER COLUMN job_id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_support_members  ALTER COLUMN member_id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_support_teams    ALTER COLUMN team_id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_product_bins     ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.sw_term_limit       ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.dashboard_role_menu ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.va_trans_request    ALTER COLUMN tran_nr DROP IDENTITY IF EXISTS;
