CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903075028_InitialAuthModule') THEN
    CREATE TABLE public.api_refresh_token (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserName" text NOT NULL,
        "TokenHash" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "RevokedAt" timestamp with time zone,
        "ReplacedByTokenHash" text,
        "CreatedByIp" text,
        CONSTRAINT "PK_api_refresh_token" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903075028_InitialAuthModule') THEN
    CREATE TABLE public.api_token_blacklist (
        "Jti" text NOT NULL,
        "UserName" text NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "RevokedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_api_token_blacklist" PRIMARY KEY ("Jti")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903075028_InitialAuthModule') THEN
    CREATE INDEX "IX_api_refresh_token_TokenHash" ON public.api_refresh_token ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903075028_InitialAuthModule') THEN
    CREATE INDEX "IX_api_refresh_token_UserName" ON public.api_refresh_token ("UserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903075028_InitialAuthModule') THEN
    CREATE INDEX "IX_api_token_blacklist_ExpiresAt" ON public.api_token_blacklist ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903075028_InitialAuthModule') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260903075028_InitialAuthModule', '10.0.11');
    END IF;
END $EF$;
COMMIT;

