using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using SyncNetApi.Common;
using SyncNetApi.Data;
using SyncNetApi.Dtos.ProductPromotions;
using SyncNetApi.Entities;
using SyncNetApi.Services.Audit;

namespace SyncNetApi.Services.ProductPromotions
{
    public class ProductPromotionService : IProductPromotionService
    {
        private readonly SyncNetDbContext _context;
        private readonly IAuditService _audit;

        public ProductPromotionService(SyncNetDbContext context, IAuditService audit)
        {
            _context = context;
            _audit = audit;
        }

        // Mirrors legacy ProductFeesPromoGetRecords — INNER JOIN Product Master.
        public async Task<IReadOnlyList<ProductPromotionDto>> GetRecordsAsync(string? filter = null)
        {
            var query = from x in _context.FeesPromos.AsNoTracking()
                        join p in _context.Products.AsNoTracking() on x.product_id equals p.product_code
                        select new { x, ProductName = p.product_name };

            if (!string.IsNullOrWhiteSpace(filter))
            {
                var f = filter.Sanitize().ToLower();
                query = query.Where(r => (r.x.product_id ?? "").ToLower().Contains(f)
                    || (r.ProductName ?? "").ToLower().Contains(f)
                    || (r.x.promo_code ?? "").ToLower().Contains(f));
            }

            var list = await query.OrderBy(r => r.x.id).ToListAsync();
            return list.Select(r => ToDto(r.x, r.ProductName)).ToList();
        }

        public async Task<ProductPromotionDto?> GetByIdAsync(long id)
        {
            var entity = await _context.FeesPromos.AsNoTracking().FirstOrDefaultAsync(x => x.id == id);
            if (entity == null) return null;

            var productName = await _context.Products.AsNoTracking()
                .Where(p => p.product_code == entity.product_id).Select(p => p.product_name).FirstOrDefaultAsync();
            return ToDto(entity, productName);
        }

        public async Task<ProductPromotionDto> CreateAsync(CreateProductPromotionRequest request, string actingUser)
        {
            if (request.DateEnd < request.DateStart)
                throw new ValidationException("Range period is not valid.");

            if (!await _context.Products.AsNoTracking().AnyAsync(p => p.product_code == request.ProductId))
                throw new ValidationException($"Product '{request.ProductId}' does not exist.");

            ValidateFeeTotals(request.FeeType, request.FixedFee, request.FixedFeeAcq, request.FixedFeeIss, request.FixedFeeSwt,
                request.PercentFeeAcq, request.PercentFeeIss, request.PercentFeeSwt);

            if (await IsOverlapAsync(request.ProductId, request.DateStart, request.DateEnd, excludeId: null))
                throw new ConflictException("Active promotions for this product already exist in the same period.");

            // id is GENERATED BY DEFAULT AS IDENTITY — do not assign manually (see entity note).
            var entity = new SwFeesPromo
            {
                product_id = request.ProductId,
                promo_code = request.PromoCode,
                promo_desc = request.PromoDesc,
                date_start = request.DateStart,
                date_end = request.DateEnd,
                fee_type = request.FeeType,
                fixed_fee = request.FixedFee,
                fixed_fee_acq = request.FixedFeeAcq,
                fixed_fee_iss = request.FixedFeeIss,
                fixed_fee_swt = request.FixedFeeSwt,
                percent_fee = request.PercentFee,
                percent_fee_acq = request.PercentFeeAcq,
                percent_fee_iss = request.PercentFeeIss,
                percent_fee_swt = request.PercentFeeSwt,
                is_active = request.IsActive
            };

            _context.FeesPromos.Add(entity);
            await _context.SaveChangesAsync();

            _audit.LogInsert(entity, "sw_fees_promo", actingUser);
            await _context.SaveChangesAsync();

            var productName = await _context.Products.AsNoTracking()
                .Where(p => p.product_code == entity.product_id).Select(p => p.product_name).FirstOrDefaultAsync();
            return ToDto(entity, productName);
        }

        public async Task<ProductPromotionDto> UpdateAsync(long id, UpdateProductPromotionRequest request, string actingUser)
        {
            var entity = await _context.FeesPromos.FirstOrDefaultAsync(x => x.id == id)
                ?? throw new NotFoundException($"Product promo '{id}' not found.");

            ValidateFeeTotals(request.FeeType, request.FixedFee, request.FixedFeeAcq, request.FixedFeeIss, request.FixedFeeSwt,
                request.PercentFeeAcq, request.PercentFeeIss, request.PercentFeeSwt);

            // Dates/ProductId are immutable, but re-run the same overlap guard as legacy Save()
            // does unconditionally on every save — activating a promo again can still collide
            // with another active promo in the same period.
            if (await IsOverlapAsync(entity.product_id, entity.date_start, entity.date_end, excludeId: id))
                throw new ConflictException("Active promotions for this product already exist in the same period.");

            var before = ToDto(entity, null);
            entity.fee_type = request.FeeType;
            entity.fixed_fee = request.FixedFee;
            entity.fixed_fee_acq = request.FixedFeeAcq;
            entity.fixed_fee_iss = request.FixedFeeIss;
            entity.fixed_fee_swt = request.FixedFeeSwt;
            entity.percent_fee = request.PercentFee;
            entity.percent_fee_acq = request.PercentFeeAcq;
            entity.percent_fee_iss = request.PercentFeeIss;
            entity.percent_fee_swt = request.PercentFeeSwt;
            entity.is_active = request.IsActive;

            _audit.LogUpdate(before, ToDto(entity, null), "sw_fees_promo", actingUser);

            await _context.SaveChangesAsync();
            return ToDto(entity, null);
        }

        public async Task DeleteAsync(long id, string actingUser)
        {
            var entity = await _context.FeesPromos.FirstOrDefaultAsync(x => x.id == id)
                ?? throw new NotFoundException($"Product promo '{id}' not found.");

            _context.FeesPromos.Remove(entity);
            _audit.LogDelete(entity, "sw_fees_promo", actingUser);

            await _context.SaveChangesAsync();
        }

        // Mirrors legacy ProductFeesPromoIsOverlapAsync — only active rows are checked,
        // standard interval overlap, scoped per product, excludes own id.
        private async Task<bool> IsOverlapAsync(string? productId, System.DateTime dateStart, System.DateTime dateEnd, long? excludeId)
        {
            var query = _context.FeesPromos.AsNoTracking().Where(p => p.product_id == productId && p.is_active);
            if (excludeId.HasValue)
                query = query.Where(p => p.id != excludeId.Value);

            return await query.AnyAsync(p => p.date_start <= dateEnd && p.date_end >= dateStart);
        }

        // Mirrors legacy IsValid(): Fixed fees must sum exactly to FixedFee; Percent fees must
        // sum exactly to 100.
        private static void ValidateFeeTotals(string feeType, int? fixedFee, int? fixedFeeAcq, int? fixedFeeIss, int? fixedFeeSwt,
            decimal? percentFeeAcq, decimal? percentFeeIss, decimal? percentFeeSwt)
        {
            if (feeType == "0")
            {
                var totalFixed = (fixedFeeAcq ?? 0) + (fixedFeeIss ?? 0) + (fixedFeeSwt ?? 0);
                if (totalFixed != (fixedFee ?? 0))
                    throw new ValidationException($"Total merchant, sub merchant and switch fees must be IDR {fixedFee ?? 0}.");
            }
            else
            {
                var totalPercent = (percentFeeAcq ?? 0) + (percentFeeIss ?? 0) + (percentFeeSwt ?? 0);
                if (totalPercent != 100)
                    throw new ValidationException("Total merchant, sub merchant and switch fees must be 100%.");
            }
        }

        private static ProductPromotionDto ToDto(SwFeesPromo e, string? productName) => new(
            e.id, e.product_id, productName, e.promo_code, e.promo_desc, e.date_start, e.date_end,
            e.fee_type ?? "0", e.fixed_fee, e.fixed_fee_acq, e.fixed_fee_iss, e.fixed_fee_swt,
            e.percent_fee, e.percent_fee_acq, e.percent_fee_iss, e.percent_fee_swt, e.is_active);
    }
}
