using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using SyncNetApi.Common;
using SyncNetApi.Data;
using SyncNetApi.Dtos.ProductFeeTierings;
using SyncNetApi.Entities;
using SyncNetApi.Services.Audit;

namespace SyncNetApi.Services.ProductFeeTierings
{
    public class ProductFeeTieringService : IProductFeeTieringService
    {
        private readonly SyncNetDbContext _context;
        private readonly IAuditService _audit;

        public ProductFeeTieringService(SyncNetDbContext context, IAuditService audit)
        {
            _context = context;
            _audit = audit;
        }

        // Mirrors legacy ProductFeesTieringGetRecords — INNER JOIN Product Master.
        public async Task<IReadOnlyList<ProductFeeTieringDto>> GetRecordsAsync(string? filter = null)
        {
            var query = from x in _context.FeesTierings.AsNoTracking()
                        join p in _context.Products.AsNoTracking() on x.product_id equals p.product_code
                        select new { x, ProductName = p.product_name };

            if (!string.IsNullOrWhiteSpace(filter))
            {
                var f = filter.Sanitize().ToLower();
                query = query.Where(r => (r.x.product_id ?? "").ToLower().Contains(f)
                    || (r.ProductName ?? "").ToLower().Contains(f));
            }

            var list = await query.OrderBy(r => r.x.product_id).ThenBy(r => r.x.tier_level).ToListAsync();
            return list.Select(r => ToDto(r.x, r.ProductName)).ToList();
        }

        public async Task<ProductFeeTieringDto?> GetByIdAsync(long id)
        {
            var entity = await _context.FeesTierings.AsNoTracking().FirstOrDefaultAsync(x => x.id == id);
            if (entity == null) return null;

            var productName = await _context.Products.AsNoTracking()
                .Where(p => p.product_code == entity.product_id).Select(p => p.product_name).FirstOrDefaultAsync();
            return ToDto(entity, productName);
        }

        public async Task<ProductFeeTieringDto> CreateAsync(CreateProductFeeTieringRequest request, string actingUser)
        {
            if (!await _context.Products.AsNoTracking().AnyAsync(p => p.product_code == request.ProductId))
                throw new ValidationException($"Product '{request.ProductId}' does not exist.");

            if (await IsDuplicateTierAsync(request.ProductId, request.TierLevel, excludeId: null))
                throw new ConflictException("Duplicate product id and tier level.");

            if (await IsOverlapAsync(request.ProductId, request.MinTran, request.MaxTran, excludeId: null))
                throw new ConflictException("Transaction range overlaps with existing products and tiers.");

            ValidateFeeTotals(request.FeeType, request.FixedFee, request.FixedFeeAcq, request.FixedFeeIss, request.FixedFeeSwt,
                request.PercentFeeAcq, request.PercentFeeIss, request.PercentFeeSwt);

            // id is GENERATED BY DEFAULT AS IDENTITY — do not assign manually (see entity note).
            var entity = new SwFeesTiering
            {
                product_id = request.ProductId,
                tier_level = request.TierLevel,
                min_tran = request.MinTran,
                max_tran = request.MaxTran,
                fee_type = request.FeeType,
                fixed_fee = request.FixedFee,
                fixed_fee_acq = request.FixedFeeAcq,
                fixed_fee_iss = request.FixedFeeIss,
                fixed_fee_swt = request.FixedFeeSwt,
                percent_fee = request.PercentFee,
                percent_fee_acq = request.PercentFeeAcq,
                percent_fee_iss = request.PercentFeeIss,
                percent_fee_swt = request.PercentFeeSwt
            };

            _context.FeesTierings.Add(entity);
            await _context.SaveChangesAsync();

            _audit.LogInsert(entity, "sw_fees_tiering", actingUser);
            await _context.SaveChangesAsync();

            var productName = await _context.Products.AsNoTracking()
                .Where(p => p.product_code == entity.product_id).Select(p => p.product_name).FirstOrDefaultAsync();
            return ToDto(entity, productName);
        }

        public async Task<ProductFeeTieringDto> UpdateAsync(long id, UpdateProductFeeTieringRequest request, string actingUser)
        {
            var entity = await _context.FeesTierings.FirstOrDefaultAsync(x => x.id == id)
                ?? throw new NotFoundException($"Tiering fee '{id}' not found.");

            // ProductId/TierLevel are immutable, but MinTran/MaxTran can change — re-run the
            // same overlap guard as legacy Save() does unconditionally on every save.
            if (await IsDuplicateTierAsync(entity.product_id, entity.tier_level, excludeId: id))
                throw new ConflictException("Duplicate product id and tier level.");

            if (await IsOverlapAsync(entity.product_id, request.MinTran, request.MaxTran, excludeId: id))
                throw new ConflictException("Transaction range overlaps with existing products and tiers.");

            ValidateFeeTotals(request.FeeType, request.FixedFee, request.FixedFeeAcq, request.FixedFeeIss, request.FixedFeeSwt,
                request.PercentFeeAcq, request.PercentFeeIss, request.PercentFeeSwt);

            var before = ToDto(entity, null);
            entity.min_tran = request.MinTran;
            entity.max_tran = request.MaxTran;
            entity.fee_type = request.FeeType;
            entity.fixed_fee = request.FixedFee;
            entity.fixed_fee_acq = request.FixedFeeAcq;
            entity.fixed_fee_iss = request.FixedFeeIss;
            entity.fixed_fee_swt = request.FixedFeeSwt;
            entity.percent_fee = request.PercentFee;
            entity.percent_fee_acq = request.PercentFeeAcq;
            entity.percent_fee_iss = request.PercentFeeIss;
            entity.percent_fee_swt = request.PercentFeeSwt;

            _audit.LogUpdate(before, ToDto(entity, null), "sw_fees_tiering", actingUser);

            await _context.SaveChangesAsync();
            return ToDto(entity, null);
        }

        public async Task DeleteAsync(long id, string actingUser)
        {
            var entity = await _context.FeesTierings.FirstOrDefaultAsync(x => x.id == id)
                ?? throw new NotFoundException($"Tiering fee '{id}' not found.");

            _context.FeesTierings.Remove(entity);
            _audit.LogDelete(entity, "sw_fees_tiering", actingUser);

            await _context.SaveChangesAsync();
        }

        private async Task<bool> IsDuplicateTierAsync(string? productId, int tierLevel, long? excludeId)
        {
            var query = _context.FeesTierings.AsNoTracking().Where(p => p.product_id == productId && p.tier_level == tierLevel);
            if (excludeId.HasValue)
                query = query.Where(p => p.id != excludeId.Value);
            return await query.AnyAsync();
        }

        // Mirrors legacy ProductFeesTieringIsOverlapAsync exactly, including its quirk: a row
        // with NULL min/max never satisfies `>=`/`<=` against another row's values, so it can
        // never register as overlapping (matches legacy's raw `long?` comparison behavior).
        private async Task<bool> IsOverlapAsync(string? productId, long? minTran, long? maxTran, long? excludeId)
        {
            var query = _context.FeesTierings.AsNoTracking().Where(p => p.product_id == productId);
            if (excludeId.HasValue)
                query = query.Where(p => p.id != excludeId.Value);

            return await query.AnyAsync(p => p.max_tran >= minTran && p.min_tran <= maxTran);
        }

        // Mirrors legacy IsValid(): Fixed fees must sum exactly to FixedFee; Percent fees must
        // sum exactly to 100.
        private static void ValidateFeeTotals(string feeType, int? fixedFee, int? fixedFeeAcq, int? fixedFeeIss, int? fixedFeeSwt,
            decimal? percentFeeAcq, decimal? percentFeeIss, decimal? percentFeeSwt)
        {
            if (feeType == "0")
            {
                var totalFixed = (fixedFeeAcq ?? 0) + (fixedFeeIss ?? 0) + (fixedFeeSwt ?? 0);
                if (totalFixed != (fixedFee ?? 0))
                    throw new ValidationException($"Total merchant, sub merchant and switch fees must be IDR {fixedFee ?? 0}.");
            }
            else
            {
                var totalPercent = (percentFeeAcq ?? 0) + (percentFeeIss ?? 0) + (percentFeeSwt ?? 0);
                if (totalPercent != 100)
                    throw new ValidationException("Total merchant, sub merchant and switch fees must be 100%.");
            }
        }

        private static ProductFeeTieringDto ToDto(SwFeesTiering e, string? productName) => new(
            e.id, e.product_id, productName, e.tier_level, e.min_tran, e.max_tran,
            e.fee_type ?? "0", e.fixed_fee, e.fixed_fee_acq, e.fixed_fee_iss, e.fixed_fee_swt,
            e.percent_fee, e.percent_fee_acq, e.percent_fee_iss, e.percent_fee_swt);
    }
}
