using System.ComponentModel.DataAnnotations;

namespace SyncNetApi.Dtos.Provinces
{
    /// <summary>Id is generated by Postgres (GENERATED ALWAYS AS IDENTITY) — never supplied by
    /// the caller. province/capital/island are all varchar(50) — real column widths.</summary>
    public class CreateProvinceRequest
    {
        [Required, MaxLength(50)]
        public string Province { get; set; } = string.Empty;

        [MaxLength(50)]
        public string? Capital { get; set; }

        [MaxLength(50)]
        public string? Island { get; set; }
    }
}
