<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>SyncNetCore</AssemblyName>
    <RootNamespace>SyncNet</RootNamespace>
    <StartupObject>SyncNet.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Cams\**" />
    <Compile Remove="HSMBackup\**" />
    <EmbeddedResource Remove="Cams\**" />
    <EmbeddedResource Remove="HSMBackup\**" />
    <None Remove="Cams\**" />
    <None Remove="HSMBackup\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Common\RouteByPrice.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.EventLog" Version="10.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="VERSION.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
