<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1707;CA1515;CA1861;CA2007;CA1001;CA2000;CA1849;CA5394;CA1308;CA1051;CA2234;xUnit1051</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SyncNetPro.Sdk.Testing\SyncNetPro.Sdk.Testing.csproj" />
    <ProjectReference Include="..\..\tools\SyncNetPro.SimCore\SyncNetPro.SimCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
