using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SyncNetApi.Entities
{
    /// <summary>Table "sw_fees_promo" — menu "Product &gt; Pricing &amp; Fees &gt; Promotions"
    /// (`/product/pricing-fees/promotions`). `id` (bigint) is `GENERATED BY DEFAULT AS IDENTITY` (verified
    /// live) — do not assign manually. `ProductId`/`PromoCode`/`PromoDesc`/`DateStart`/
    /// `DateEnd` are all immutable after create — legacy renders every one of them
    /// readonly/disabled on edit; only Fee Type, the fee amounts, and `IsActive` stay
    /// editable. `app_name`/`group_name`/`subgroup_name`/`merchant_id`/`submerchant_id` exist
    /// on the real table but no legacy form field ever touches them (not even a commented-out
    /// placeholder like Product Fees has for `app_name`) — left unmapped here as genuinely
    /// dead columns for this module. The real table also has `update_by`/`last_update`
    /// columns the legacy model never mapped — left unmapped too. Widths verified live:
    /// promo_code varchar(15), promo_desc varchar(255), product_id varchar(30), fee_type
    /// varchar(2).</summary>
    [Table("sw_fees_promo", Schema = "public")]
    public class SwFeesPromo
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long id { get; set; }
        public string? product_id { get; set; }
        public string? promo_code { get; set; }
        public string? promo_desc { get; set; }

        [Column(TypeName = "timestamp without time zone")]
        public DateTime date_start { get; set; }

        [Column(TypeName = "timestamp without time zone")]
        public DateTime date_end { get; set; }
        public string? fee_type { get; set; }
        public int? fixed_fee { get; set; }
        public int? fixed_fee_acq { get; set; }
        public int? fixed_fee_iss { get; set; }
        public int? fixed_fee_swt { get; set; }
        public decimal? percent_fee { get; set; }
        public decimal? percent_fee_acq { get; set; }
        public decimal? percent_fee_iss { get; set; }
        public decimal? percent_fee_swt { get; set; }
        public bool is_active { get; set; }
    }
}
