using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SyncNetApi.Entities
{
    /// <summary>Table "sw_fees" — menu "Product &gt; Pricing &amp; Fees &gt; Postpaid Fees" (`/product/pricing-fees/postpaid-fees`).
    /// `id` (bigint) is `GENERATED BY DEFAULT AS IDENTITY` (verified live) — do not assign
    /// manually. All relation fields (`product_id`, `merchant_id`, `submerchant_id`,
    /// `group_name`, `subgroup_name`) are immutable after create — legacy renders all of them
    /// readonly/disabled on edit, only Fee Type and the fee amounts stay editable. `app_name`
    /// exists on the real table but its field is commented out in the legacy form entirely —
    /// left unmapped here too (dead column for this module). `merchant_id`/`submerchant_id`
    /// are optional (legacy only validates existence when non-empty, no requiredness check).
    /// The real table also has `update_by`/`last_update` columns the legacy model never
    /// mapped — left unmapped. Widths verified live: product_id varchar(30), merchant_id
    /// varchar(15), submerchant_id/group_name/subgroup_name varchar(50)/varchar(30) mixed —
    /// see individual properties.</summary>
    [Table("sw_fees", Schema = "public")]
    public class SwFees
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long id { get; set; }
        public string? product_id { get; set; }
        public string? merchant_id { get; set; }
        public string? submerchant_id { get; set; }
        public string? group_name { get; set; }
        public string? subgroup_name { get; set; }
        public string? fee_type { get; set; }
        public int? fixed_fee { get; set; }
        /// <summary>Fee Loket (transaksi fee_acq).</summary>
        public int? fixed_fee_acq { get; set; }
        /// <summary>Fee Mitra (transaksi fee_mer).</summary>
        public int? fixed_fee_mer { get; set; }
        public int? fixed_fee_iss { get; set; }
        /// <summary>Fee Biller (transaksi fee_bil). Diinput bila routing_mode STATIC; mode
        /// dynamic menghitungnya dari sharing fee biller.</summary>
        public int? fixed_fee_bil { get; set; }
        /// <summary>Fee perusahaan (transaksi fee_swt). Diinput bila STATIC.</summary>
        public int? fixed_fee_swt { get; set; }
        public decimal? percent_fee { get; set; }
        public decimal? percent_fee_acq { get; set; }
        public decimal? percent_fee_mer { get; set; }
        public decimal? percent_fee_iss { get; set; }
        public decimal? percent_fee_bil { get; set; }
        public decimal? percent_fee_swt { get; set; }
        /// <summary>STATIC / PRIORITY / BEST_PRICE / LOAD_BALANCE. NULL di baris per CA = Ikuti
        /// Default (mode baris default produk).</summary>
        public string? routing_mode { get; set; }
        /// <summary>Biller untuk mode STATIC (sw_nodes.node_id). NULL = primary.</summary>
        public int? static_node_id { get; set; }
    }
}
