using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SyncNetApi.Entities
{
    /// <summary>Table "sw_fees_tiering" — menu "Product &gt; Pricing &amp; Fees &gt; Volume &amp; Tiering"
    /// (`/product/pricing-fees/volume-tiering`). `id` (bigint) is `GENERATED BY DEFAULT AS IDENTITY` (verified
    /// live) — do not assign manually. `ProductId`/`TierLevel` are immutable after create —
    /// legacy renders both readonly/disabled on edit; `MinTran`/`MaxTran` stay editable even
    /// after create (unlike most other fields in this Fees group). `min_amount`/`max_amount`
    /// exist on the real table but no legacy form field ever touches them — left unmapped
    /// here as dead columns. The real table also has `update_by`/`last_update` columns the
    /// legacy model never mapped — left unmapped too. Widths verified live: product_id
    /// varchar(30), fee_type varchar(2).</summary>
    [Table("sw_fees_tiering", Schema = "public")]
    public class SwFeesTiering
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long id { get; set; }
        public string? product_id { get; set; }
        public int tier_level { get; set; }
        public long? min_tran { get; set; }
        public long? max_tran { get; set; }
        public string? fee_type { get; set; }
        public int? fixed_fee { get; set; }
        public int? fixed_fee_acq { get; set; }
        public int? fixed_fee_iss { get; set; }
        public int? fixed_fee_swt { get; set; }
        public decimal? percent_fee { get; set; }
        public decimal? percent_fee_acq { get; set; }
        public decimal? percent_fee_iss { get; set; }
        public decimal? percent_fee_swt { get; set; }
    }
}
