using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SyncNetApi.Entities
{
    /// <summary>Table "sw_job_fee_detail" — Configuration &gt; Jobs &gt; Job Fee detail rows,
    /// new in Phase 5e. id is bigint, GENERATED BY DEFAULT AS IDENTITY — never set it
    /// explicitly. job_id is int (matches sw_job_fee.id cast to int — realistic since job fee
    /// ids won't approach int.MaxValue) with NO real Postgres FK constraint (verified live) —
    /// cascade delete when the parent sw_job_fee row is removed is done manually in the
    /// service layer. fee_type: "0" Fixed / "1" Percent.</summary>
    [Table("sw_job_fee_detail", Schema = "public")]
    public class SwJobFeeDetail
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long id { get; set; }
        public int job_id { get; set; }
        public string? product_id { get; set; }
        public string? group_name { get; set; }
        public string? subgroup_name { get; set; }
        public string? merchant_id { get; set; }
        public string? submerchant_id { get; set; }
        public string? fee_type { get; set; }
        public int? fixed_fee { get; set; }
        public int? fixed_fee_acq { get; set; }
        public int? fixed_fee_iss { get; set; }
        public int? fixed_fee_swt { get; set; }
        public decimal? percent_fee { get; set; }
        public decimal? percent_fee_acq { get; set; }
        public decimal? percent_fee_iss { get; set; }
        public decimal? percent_fee_swt { get; set; }
    }
}
