using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SyncNetApi.Entities
{
    /// <summary>`sw_job_logs` — one row per Job Schedule (`sw_jobs`) run, backs Monitoring &gt;
    /// Jobs &gt; Log (dashboard_menu menu_id 7202). Read-only from this app's side: Monitoring
    /// never writes here (rows are produced by the job runner itself, out of scope). `job_nr`
    /// verified live as bigint `GENERATED BY DEFAULT AS IDENTITY` — irrelevant for our read-only
    /// usage but documented for consistency with the rest of the project's identity-quirk
    /// notes. Column `server_name` exists on the real table but is never read by legacy
    /// `JobLogGetRecords`/`VwJobLog` — dead column here too, not mapped.</summary>
    [Table("sw_job_logs", Schema = "public")]
    public class SwJobLog
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long job_nr { get; set; }

        public int job_id { get; set; }
        public DateTime? datetime_begin { get; set; }
        public DateTime? datetime_end { get; set; }
        public int result_value { get; set; }
        public string? status { get; set; }
    }
}
