using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SyncNetApi.Entities
{
    /// <summary>Table "sw_job_fee" — Configuration &gt; Jobs &gt; Job Fee, new in Phase 5e.
    /// id is bigint, GENERATED BY DEFAULT AS IDENTITY (verified live via information_schema) —
    /// never set it explicitly, let Postgres generate. job_status: "0" Scheduled / "1" Done.
    /// Matches legacy read-only-after-create behavior (SyncNetBlazorServer
    /// Jobs/Fees/Detail.razor has no Update path) — this API exposes Create/Read/Delete only,
    /// no Update. 0 rows currently. No DB-level FK to sw_job_fee_detail — cascade delete of
    /// details is done manually in the service layer.</summary>
    [Table("sw_job_fee", Schema = "public")]
    public class SwJobFee
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long id { get; set; }
        public string? job_desc { get; set; }
        public string? job_status { get; set; }
        public DateTime? scheduled_at { get; set; }
        public DateTime? created_at { get; set; }
    }
}
