using System.Collections.Generic;

namespace SyncNetApi.Services.Hsm
{
    /// <summary>Port of legacy Library/NbHSM.cs's "HSM Emulator" region — the only region of
    /// NbHSM that was ever actually used (the "Interface &amp; Terminal Config" region wrapped
    /// the exact same primitives for Master/Session key generation, now reused here too, see
    /// KeyManagementController). All math runs under LMK_1 loaded from the legacy Resources.bin
    /// via LegacyResourcesLoader. Every method throws HsmUnavailableException if the LMK isn't
    /// loaded — deliberately NOT the legacy fallback of silently returning zero-padded values,
    /// since a caller receiving "00000000..." back as a "generated key" and using it for real
    /// is a worse failure mode than an explicit error.</summary>
    public interface IHsmCryptoProvider
    {
        bool IsAvailable { get; }

        /// <summary>lengthHexChars must be 16, 32 or 48. parity: "none" (default, plain CSPRNG
        /// hex), "odd" or "even" — legacy's parity check is on the generated byte's numeric
        /// value (value % 2), not true DES key-parity bit counting; replicated as-is.</summary>
        HsmComponentResult GenerateComponent(int lengthHexChars, string parity);

        /// <summary>KCV of a clear-text component: leftmost 3 bytes of encrypting an all-zero
        /// block under the component itself used as a key.</summary>
        string GetKeyCheckValue(string clearHex);

        /// <summary>KCV of a component that is itself encrypted under LMK_1 — decrypts first,
        /// then computes GetKeyCheckValue of the clear value.</summary>
        string GetKeyCheckValueUnderLmk(string encryptedHex);

        /// <summary>Encrypts a clear component under LMK_1.</summary>
        string GetKeyEncrypted(string clearHex);

        /// <summary>Decrypts a component that is encrypted under LMK_1.</summary>
        string GetClearKey(string encryptedHex);

        /// <summary>Forms a ZMK from 1+ components: XORs them together (decrypting each under
        /// LMK_1 first when inputMode is "encrypted"), encrypts the XOR result under LMK_1, and
        /// returns its KCV (of the CLEAR xor result, matching legacy exactly).</summary>
        HsmZmkResult GenerateZmk(IReadOnlyList<string> components, string inputMode);

        /// <summary>keyLength: "1"=Single (8 bytes/16 hex), "2"=Double (16 bytes/32 hex),
        /// "3"=Triple (24 bytes/48 hex).</summary>
        HsmMasterKeyResult GenerateMasterKey(string keyLength);

        /// <summary>masterKeyUnderLmk is the caller's already-generated Master Key value
        /// (encrypted under LMK_1) — session key length matches its hex length. Decrypts it to
        /// get the clear ZMK, generates a random clear session key, and returns it wrapped
        /// under LMK_1 and under the clear ZMK, plus its KCV.</summary>
        HsmSessionKeyResult GenerateSessionKey(string masterKeyUnderLmk);
    }
}
