using System.ComponentModel.DataAnnotations;

namespace SyncNetApi.Dtos.Cities
{
    /// <summary>Id is generated by Postgres (GENERATED ALWAYS AS IDENTITY) — never supplied by
    /// the caller. city/province are varchar(50), city_type is varchar(1) — real column widths.</summary>
    public class CreateCityRequest
    {
        [Required, MaxLength(50)]
        public string City { get; set; } = string.Empty;

        [MaxLength(50)]
        public string? Province { get; set; }

        [MaxLength(1)]
        public string? CityType { get; set; }
    }
}
